// GENERATED by tools/packs/build.mjs — the current downloadable pack for this
// game. `key` is the versioned CDN folder (content-hashed, so every rebuild is
// a new immutable path and old ones stay valid for players mid-download).
export const PACK = { key: "games/trackline/p-aa6c1bea08", version: "p-aa6c1bea08", bytes: 54278 } as const;
