// GENERATED by tools/packs/build.mjs — the current downloadable pack for this
// game. `key` is the versioned CDN folder (content-hashed, so every rebuild is
// a new immutable path and old ones stay valid for players mid-download).
export const PACK = { key: "games/trackline/p-04ee2abbbf", version: "p-04ee2abbbf", bytes: 4418336 } as const;
