#!/usr/bin/env node
// Build a game's pack: content-hash every file under tools/packs/<game>/src,
// derive the version from the hashes, write out/games/<game>/<version>/ with
// a manifest.json, and point backend/src/games/<game>/pack.ts at it.
import { createHash } from "node:crypto";
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "../..");
const gameId = process.argv[2];
if (!gameId) {
  console.error("usage: node tools/packs/build.mjs <gameId>");
  process.exit(2);
}
const src = path.join(here, gameId, "src");
const outRoot = path.join(here, "out");

async function walk(dir, base = dir) {
  const out = [];
  for (const e of await fs.readdir(dir, { withFileTypes: true })) {
    if (e.name.startsWith(".")) continue;
    const full = path.join(dir, e.name);
    if (e.isDirectory()) out.push(...(await walk(full, base)));
    else if (!e.name.endsWith(".py") && !e.name.endsWith(".md")) out.push(path.relative(base, full).split(path.sep).join("/"));
  }
  return out.sort();
}

const files = await walk(src);
if (files.length === 0) {
  console.error(`no files under ${src}`);
  process.exit(1);
}
const entries = [];
const versionHash = createHash("sha256");
for (const rel of files) {
  const body = await fs.readFile(path.join(src, rel));
  const sha = createHash("sha256").update(body).digest("hex");
  versionHash.update(rel).update("\0").update(sha).update("\0");
  entries.push({ path: rel, bytes: body.length, sha256: sha, body });
}
const version = `p-${versionHash.digest("hex").slice(0, 10)}`;
const key = `games/${gameId}/${version}`;
const dest = path.join(outRoot, key);
await fs.rm(path.join(outRoot, "games", gameId), { recursive: true, force: true });
await fs.mkdir(dest, { recursive: true });
let total = 0;
for (const e of entries) {
  await fs.mkdir(path.dirname(path.join(dest, e.path)), { recursive: true });
  await fs.writeFile(path.join(dest, e.path), e.body);
  total += e.bytes;
}
const manifest = {
  game: gameId,
  version,
  files: entries.map(({ path: p, bytes, sha256 }) => ({ path: p, bytes, sha256 })),
  totalBytes: total,
};
const manifestBody = Buffer.from(JSON.stringify(manifest, null, 2) + "\n");
await fs.writeFile(path.join(dest, "manifest.json"), manifestBody);

const packTs = `// GENERATED by tools/packs/build.mjs — the current downloadable pack for this
// game. \`key\` is the versioned CDN folder (content-hashed, so every rebuild is
// a new immutable path and old ones stay valid for players mid-download).
export const PACK = { key: "${key}", version: "${version}", bytes: ${total} } as const;
`;
const packTsPath = path.join(root, "backend", "src", "games", gameId, "pack.ts");
await fs.mkdir(path.dirname(packTsPath), { recursive: true });
await fs.writeFile(packTsPath, packTs);
console.log(`pack ${gameId} ${version}: ${entries.length} files, ${(total / 1024).toFixed(1)} KB (+ manifest ${manifestBody.length} B)`);
console.log(`  out:  ${path.relative(root, dest)}`);
console.log(`  wrote ${path.relative(root, packTsPath)}`);
