// GENERATED by tools/packs/build.mjs — the current downloadable pack for this
// game. `key` is the versioned CDN folder (content-hashed, so every rebuild is
// a new immutable path and old ones stay valid for players mid-download).
export const PACK = { key: "games/social/p-45dbe3d73b", version: "p-45dbe3d73b", bytes: 4695924 } as const;
