#!/usr/bin/env node
// Copies /shared into frontend/src/shared and backend/src/shared.
//
//   node scripts/sync-shared.mjs                # sync both once
//   node scripts/sync-shared.mjs --target=frontend  (or backend)
//   node scripts/sync-shared.mjs --watch        # sync, then keep syncing on change
//   node scripts/sync-shared.mjs --check        # exit 1 if a copy is stale (CI)
//
// The copies are git-ignored and regenerated by every dev/build/typecheck
// script on both sides, so each side compiles shared code with plain relative
// imports and no build coupling. Stale files in a copy are deleted; every
// copied file gets a banner so an accidental edit is obviously in the wrong
// place. Zero dependencies — plain Node.
import { promises as fs } from "node:fs";
import { watch } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const SRC = path.join(root, "shared");
const TARGETS = {
  frontend: path.join(root, "frontend", "src", "shared"),
  backend: path.join(root, "backend", "src", "shared"),
};

const args = new Set(process.argv.slice(2));
const targetArg = [...args].find((a) => a.startsWith("--target="))?.slice(9);
const targets = targetArg ? { [targetArg]: TARGETS[targetArg] } : TARGETS;
if (targetArg && !TARGETS[targetArg]) {
  console.error(`sync-shared: unknown target "${targetArg}" (frontend | backend)`);
  process.exit(2);
}

const BANNER = (rel) =>
  `// GENERATED from /shared/${rel} by scripts/sync-shared.mjs — DO NOT EDIT HERE.\n` +
  `// Edit the file in /shared; this copy is overwritten on every dev/build/typecheck.\n`;

async function listFiles(dir, base = dir) {
  const out = [];
  let entries;
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const e of entries) {
    if (e.name === "node_modules" || e.name.startsWith(".")) continue;
    const full = path.join(dir, e.name);
    if (e.isDirectory()) out.push(...(await listFiles(full, base)));
    else if (/\.(ts|json)$/.test(e.name) && !e.name.endsWith(".d.ts")) out.push(path.relative(base, full));
  }
  return out;
}

async function render(rel) {
  const body = await fs.readFile(path.join(SRC, rel), "utf8");
  return rel.endsWith(".ts") ? BANNER(rel) + body : body;
}

async function syncOnce({ check = false } = {}) {
  const files = await listFiles(SRC);
  let stale = 0;
  for (const [name, dest] of Object.entries(targets)) {
    const wanted = new Set(files);
    // Write / update.
    for (const rel of files) {
      const content = await render(rel);
      const target = path.join(dest, rel);
      let current = null;
      try {
        current = await fs.readFile(target, "utf8");
      } catch {
        /* missing */
      }
      if (current === content) continue;
      stale++;
      if (check) {
        console.log(`  stale: ${name}/src/shared/${rel}`);
        continue;
      }
      await fs.mkdir(path.dirname(target), { recursive: true });
      await fs.writeFile(target, content);
    }
    // Delete leftovers.
    for (const rel of await listFiles(dest)) {
      if (wanted.has(rel)) continue;
      stale++;
      if (check) {
        console.log(`  leftover: ${name}/src/shared/${rel}`);
        continue;
      }
      await fs.rm(path.join(dest, rel), { force: true });
    }
    if (!check) {
      await fs.mkdir(dest, { recursive: true });
      await fs.writeFile(
        path.join(dest, "README-GENERATED.md"),
        "Generated copy of /shared — do not edit. See shared/README.md.\n"
      );
    }
  }
  return stale;
}

const stale = await syncOnce({ check: args.has("--check") });
if (args.has("--check")) {
  if (stale) {
    console.error(`sync-shared: ${stale} file(s) out of date — run: node scripts/sync-shared.mjs`);
    process.exit(1);
  }
  console.log("sync-shared: up to date");
  process.exit(0);
}
if (stale) console.log(`sync-shared: ${stale} file(s) refreshed → ${Object.keys(targets).join(", ")}`);

if (args.has("--watch")) {
  let timer = null;
  const schedule = () => {
    clearTimeout(timer);
    timer = setTimeout(() => void syncOnce().then((n) => n && console.log(`sync-shared: ${n} file(s) refreshed`)), 80);
  };
  watch(SRC, { recursive: true }, schedule);
  console.log("sync-shared: watching /shared");
}
